apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:open-cluster-management:{{ .KlusterletName }}-registration-agent
  namespace: {{ .KlusterletNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:open-cluster-management:{{ .KlusterletName }}-registration-agent
subjects:
  - kind: ServiceAccount
    name: {{ .KlusterletName }}-registration-sa
    namespace: {{ .KlusterletNamespace }}
