apiVersion: v1
kind: ServiceAccount
metadata:
<<<<<<< 249448baea60bb7d36bf7ea1c432e54623de372d:manifests/hub/hub-registration-webhook-serviceaccount.yaml
  name: {{ .HubCoreName }}-registration-webhook-sa
  namespace: {{ .HubCoreNamespace }}
=======
  name: {{ .ClusterManagerName }}-sa
  namespace: {{ .ClusterManagerNamespace }}
>>>>>>> Adopt new API updates for operator:manifests/hub/hub-serviceaccount.yaml
