apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
<<<<<<< 249448baea60bb7d36bf7ea1c432e54623de372d:manifests/hub/hub-registration-clusterrole.yaml
  name: system:open-cluster-management:{{ .HubCoreName }}-registration-controller
=======
  name: system:open-cluster-management:{{ .ClusterManagerName }}
>>>>>>> Adopt new API updates for operator:manifests/hub/hub-clusterrole.yaml
rules:
# Allow hub to monitor and update status of csr
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/status", "certificatesigningrequests/approval"]
  verbs: ["update"]
# Allow hub to get/list/watch/create/delete namespace and service account
- apiGroups: [""]
  resources: ["namespaces", "serviceaccounts", "configmaps"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
# Allow hub to manage clusterrole/clusterrolebinding/role/rolebinding
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "roles"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "escalate", "bind"]
# Allow hub to manage spokeclusters
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["spokeclusters"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["spokeclusters/status"]
  verbs: ["update", "patch"]
