apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.open-cluster-management.io/v1",
          "kind": "Klusterlet",
          "metadata": {
            "name": "klusterlet"
          },
          "spec": {
            "clusterName": "cluster1",
            "externalServerURLs": [
              {
                "url": "https://localhost"
              }
            ],
            "namespace": "open-cluster-management-agent",
            "registrationImagePullSpec": "quay.io/open-cluster-management/registration",
            "workImagePullSpec": "quay.io/open-cluster-management/work"
          }
        }
      ]
    capabilities: Basic Install
  name: klusterlet.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Klusterlet
      name: klusterlets.operator.open-cluster-management.io
      version: v1
  displayName: Klusterlet
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - configmaps
          - serviceaccounts
          verbs:
          - create
          - get
          - list
          - update
          - watch
          - patch
          - delete
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - create
          - get
          - list
          - watch
        - apiGroups:
          - ""
          - events.k8s.io
          resources:
          - events
          verbs:
          - create
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - get
          - list
          - update
          - watch
          - patch
          - delete
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - rolebindings
          verbs:
          - create
          - get
          - list
          - update
          - watch
          - patch
          - delete
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - roles
          verbs:
          - create
          - get
          - list
          - update
          - watch
          - patch
          - delete
          - escalate
          - bind
        - apiGroups:
          - nucleus.open-cluster-management.io
          resources:
          - spokecores
          verbs:
          - get
          - list
          - watch
          - update
          - patch
          - delete
        - apiGroups:
          - nucleus.open-cluster-management.io
          resources:
          - spokecores/status
          verbs:
          - update
          - patch
        serviceAccountName: klusterlet
      deployments:
      - name: klusterlet
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: klusterlet
          strategy: {}
          template:
            metadata:
              labels:
                app: klusterlet
            spec:
              containers:
              - args:
                - /nucleus
                - spoke
                image: quay.io/open-cluster-management/nucleus:latest
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8443
                    scheme: HTTPS
                  initialDelaySeconds: 2
                  periodSeconds: 10
                name: klusterlet
                readinessProbe:
                  httpGet:
                    path: /healthz
                    port: 8443
                    scheme: HTTPS
                  initialDelaySeconds: 2
                resources: {}
              serviceAccountName: klusterlet
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - open-cluster-management
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  version: 0.1.0
